PACKAGE_NAME="embark-template"
PACKAGE_SYMBOL="EMBARK_TEMPLATE"

MODULE_NAME="template"

HEADER_NAME="template.h"

SOURCE_NAME="template.c"

FUNCTION_NAME="template_run"

EXECUTABLE_NAME="embark-template"

TITLE="Embark Template"